= Using Skupper with Minikube

== Prerequisites

Skupper requires cluster-external network access in order to form connections between clusters.
Run `minikube tunnel` in the background to enable this access.

Make sure you run `minikube tunnel` with the same kubeconfig and Minikube profile you used for `minikube start`.
In the Hello World example, the tunnel is required only for the cluster containing the West namespace.

Console for West

 export KUBECONFIG=$HOME/.kube/config-west
 minikube tunnel

== Logging in

Minikube does not offer a dedicated login command, but you can re-run the `minikube start` command in each console you wish to configure.

Console for West

 export KUBECONFIG=$HOME/.kube/config-west
 minikube start

Console for East

 export KUBECONFIG=$HOME/.kube/config-east
 minikube start

== More information

* https://kubernetes.io/docs/setup/learning-environment/minikube/[Installing Kubernetes with Minikube]
* https://opensource.com/article/18/10/getting-started-minikube[Getting started with Minikube on Linux]
* https://kubernetes.io/docs/setup/[Getting started with Kubernetes]
