site_name: Skupper docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
    - navigation.sections

docs_dir: input
site_dir: output

nav:
  - Install: install/index.md
  - Overview: 
    - Introduction: overview/index.md
    - Resources: overview/resources.md
    - Routing: overview/routing.md
    - Connectivity: overview/connectivity.md
    - Load balancing: overview/load-balancing.md
    - Migrating from v1: overview/migrating.md
  - KubeCLI: 
    - Introduction:kube-cli/index.md
    - Site: kube-cli/site-configuration.md
    - Linking: kube-cli/site-linking.md
    - Services: kube-cli/service-exposure.md
  - Kube YAML:
    - Introduction:kube-yaml/index.md
    - Site: kube-yaml/site-configuration.md
    - Linking: kube-yaml/site-linking.md
    - Services: kube-yaml/service-exposure.md
  - Local Systems CLI:
    - Introduction: system-cli/index.md
    - Site: system-cli/site-configuration.md
    - Linking: system-cli/site-linking.md
    - Services: system-cli/service-exposure.md
  - Local Systems YAML:
    - Introduction: system-yaml/index.md
    - Site: system-yaml/site-configuration.md
    - Linking: system-yaml/site-linking.md
    - Services: system-yaml/service-exposure.md
  - Observability: console/index.md
  - Troubleshooting: troubleshooting/index.md

plugins:
  - search
