include::{mod-loc}attributes.adoc[]

//Category: skupper-declarative
// Type: assembly
[id="skupper-declarative"] 
= Configuring {skupper-name} sites using YAML

Using YAML files to configure {skupper-name} allows you to use source control to track and manage {skupper-name} network changes.

This procedure provides an alternative to the `skupper init` command described in xref:cli:index.adoc[].


// Type: procedure
[id="installing-using-yaml"] 
== Creating a {skupper-name} site using YAML

[role="system:abstract"]
Installing {skupper-name} using YAML provides a declarative method to create a {skupper-name} site.
You can store your YAML files in source control to track and manage {skupper-name} network changes.

.Prerequisites

* Access to a {kubernetes-flavor} cluster

.Procedure

. Log into your cluster.
If you are deploying {skupper-name} to be available for all namespaces, make sure you have `cluster-admin` privileges.

. Deploy the site controller:

* To install {skupper-name} into the current namespace deploy the site controller using the following YAML:
+
[subs=attributes+]
----
kubectl apply -f https://raw.githubusercontent.com/skupperproject/skupper/{skupper-version}/cmd/site-controller/deploy-watch-current-ns.yaml
----

* To install {skupper-name} for all namespaces:
+
.. Create a namespace named `skupper-site-controller`.

.. Deploy the site controller using the following YAML:
+
[subs=attributes+]
----
kubectl apply -f https://raw.githubusercontent.com/skupperproject/skupper/{skupper-version}/cmd/site-controller/deploy-watch-all-ns.yaml
----

. Verify the installation.
+
----
$ oc get pods
NAME                                       READY   STATUS    RESTARTS   AGE
skupper-site-controller-84694bdbb5-n8slb   1/1     Running   0          75s
----

. Create a YAML file to define the site, for example, `my-site.yaml`:
+
----
apiVersion: v1
data:
  cluster-local: "false"
  console: "true"
  console-authentication: internal
  console-user: "admin"
  console-password: "changeme"
  edge: "true"
  name: my-site
  router-console: "true"
  service-controller: "true"
  service-sync: "true"
kind: ConfigMap
metadata:
  name: skupper-site
----

. Apply the YAML file to your cluster:
+
----
kubectl apply -f ~/my-site.yml
----

.Additional information

* See the xref:yaml-reference[] section for more options.


// Type: reference
[id="yaml-reference"] 
== Site ConfigMap YAML reference

[role="system:abstract"]
Using YAML files to configure {skupper-name} requires that you understand all the fields so that you provision the site you require.

The following YAML items define a {skupper-name} site:

// # Core


name:: Specifies the name of the {skupper-name} site, defaults to namespace name.
The equivalent `skupper init` option is `--site-name=west`.

// router-mode:: edge or interior

ingress:: Specifies the ingress type, one of: [route|loadbalancer|nodeport|nginx-ingress-v1|contour-http-proxy|ingress|none]. If not specified route is used when available, otherwise loadbalancer is used.


site.ingress-annotations:: Specify annotations to the ingress.
The equivalent `skupper init` option is --ingress-annotations.

ingress-host:: Hostname or alias by which the ingress route or proxy can be reached.
The equivalent `skupper init` option is --ingress-host.

create-network-policy:: Restrict service access to site namespace.
The equivalent `skupper init` option is --create-network-policy.

routers:: Number of router replicas to start.
The equivalent `skupper init` option is --routers.

// # Console

console:: Enables the skupper console, defaults to `true`.
The equivalent `skupper init` option is `--enable-console=true`.

console-authentication:: Specifies the skupper console authentication method. The options are `openshift`, `internal`, `unsecured`.
The equivalent `skupper init` option is `--console-auth=internal`.

console-user::  Username for the `internal` authentication option.
The equivalent `skupper init` option is `--console-user=admin`.

console-password::  Password for the `internal` authentication option.
The equivalent `skupper init` option is `--console-password=changeme`.

console-ingress:: Determines if/how console is exposed outside cluster. If not specified uses value of --ingress. One of: [route|loadbalancer|nodeport|nginx-ingress-v1|contour-http-proxy|ingress|none].
The equivalent `skupper init` option is `--console-ingress`.


cluster-local:: Only accept connections from within the local cluster, defaults to `false`.
There is no equivalent `skupper init` option.

// edge: Specifies whether an edge site is created, defaults to `false`.


// router-console::  Enables the skupper console, defaults to `true`.

service-controller:: Enables the service controller, defaults to `true`.
There is no equivalent `skupper init` option.


service-sync:: Specifies whether the services exposed on this site are synchronized across the {service-network}, defaults to `true`.
There is no equivalent `skupper init` option.
