include::_artifacts/attributes.adoc[]

//Category: skupper
// Type: assembly

[id="installing-skupper"] 
= Installing Skupper

[role="system:abstract"]
After installing Skupper you can create a Skupper site.

You can install Skupper using either of the following methods:

* xref:installing-using-yaml[]
* xref:installing-using-cli[]


// Type: procedure
[id="installing-using-yaml"] 
== Installing Skupper using YAML

[role="system:abstract"]
Installing Skupper using YAML provides a declarative method to install Skupper.
You can store your YAML files in source control to track and manage Skupper network changes.

.Prerequisites

* Access to a Kubernetes cluster

. Log into your cluster.
If you are deploying Skupper to be available for all namespaces, make sure you have `cluster-admin` privileges.

. Deploy the site controller:

.. To install Skupper into the current namespace deploy the site controller using the following YAML:
+
[subs=attributes+]
----
kubectl apply -f https://raw.githubusercontent.com/skupperproject/skupper/{skupper-version}/cmd/site-controller/deploy-watch-current-ns.yaml
----

.. To install Skupper for all namespaces, deploy the site controller using the following YAML:
+
[subs=attributes+]
----
kubectl apply -f https://raw.githubusercontent.com/skupperproject/skupper/{skupper-version}/cmd/site-controller/deploy-watch-all-ns.yaml
----

. Verify the installation.
+
----
$ oc get pods
NAME                                       READY   STATUS    RESTARTS   AGE
skupper-site-controller-84694bdbb5-n8slb   1/1     Running   0          75s
----

// Type: procedure
[id="installing-using-cli"] 
== Installing Skupper using the CLI

[role="system:abstract"]
Installing Skupper using the command-line interface (CLI) provides a simple method to get started with Skupper.

.Prerequisites

* Access to a Kubernetes cluster

. Install the Skupper command-line interface.
+
--
For Linux:
[subs=attributes+]
----
$ curl -fL https://github.com/skupperproject/skupper/releases/download//skupper-cli-0.3.2-linux-amd64.tgz | tar -xzf -
----

For MacOS:
[subs=attributes+]
----
$ curl -fL https://github.com/skupperproject/skupper/releases/download/{skupper-version}/skupper-cli-0.3.2-mac-amd64.tgz | tar -xzf -
----
--

. Copy the `skupper` executable to a directory in your $PATH:
+
----
$ mkdir -p $HOME/bin
$ export PATH=$PATH:$HOME/bin
$ mv skupper $HOME/bin
----

. Verify the installation.
+
[subs=attributes+]
----
$ skupper --version
skupper version {skupper-version}
----
