= Deployment options on Kubernetes

When you create a site on Kubernetes, there are many options you can use.  For example, you can set the number of pods and the resources allocated to each pod.
This guide focusses on the following goals:

* xref:increased-traffic[]
* xref:high-availability[]

// Type:procedure
[id="increased-traffic"]
== Scaling for increased traffic

For optimal network latency and throughput, you can adjust the CPU allocation for the router using the `router-cpu` option.
Router CPU is the primary factor governing Skupper network performance.

NOTE: Increasing the number of routers does not improve network performance.  An incoming router-to-router link is associated with just one active router.  Additional routers do not receive traffic while that router is responding

. Determine the router CPU allocation you require.
+
--
By default, the router CPU allocation is `BestEffort` as described in link:https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#besteffort[Pod Quality of Service Classes].

Consider the following CPU allocation options:

[%header,cols="1,5"]
|===

|Router CPU | Description

|1
|Helps avoid issues with `BestEffort` on low resource clusters

|2
|Suitable for production environments

|5
|Maximum performance
|===


--

. If you are using the Skupper CLI, set the CPU allocation for the router using the `--router-cpu` option.  For example:
+
--
[source, bash]
----
$ skupper init --router-cpu 2
----
--

. If you are using YAML, set the CPU allocation for the router by setting a value for the `router-cpu` attribute.  For example:
+
--
[source, YAML]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: "skupper-site"
data:
  name: "my-site"
  router-cpu: 2
----
--


// Type:procedure
[id="high-availability"]
== Creating a high availability site

By default, Kubernetes restarts any router that becomes unresponsive.
(If you encounter router restarts, consider xref:increased-traffic[] in order to improve responsiveness.)

If the cluster where you are running Skupper is very busy, it may take time for Kubernetes to schedule a new router pod.  You can "preschedule" a backup router by deploying two routers in a site.

. If you are using the Skupper CLI, set the number of routers to `2` using the `--routers` option:
+
--
[source, bash]
----
$ skupper init --routers 2
----
--

. If you are using YAML, set the number of routers to `2` by setting the `routers` attribute:
+
--
[source, YAML]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: "skupper-site"
data:
  name: "my-site"
  routers: 2
----
--

Setting the number of routers to more than two does not provide increased availability and can adversely affect performance.

Note that clients must reconnect when a router restarts or traffic is
redirected to a backup router.

== Deployment recommendations

The primary factor to consider when scaling the Skupper router for your workload is router CPU.

[TIP]
====
Scale the router vertically, not horizontally.
The nature of cluster ingress and connection routing means that increasing the number of routers is not effective for improving performance. 
Increasing router CPU does improve performance.
====

Two CPU cores (2,000 millicores) per router is a good starting point. 
Two CPU cores includes some headroom and provides low latencies for a large set of workloads.

If the peak throughput required by your workload is low, it is possible to achieve satisfactory latencies with less router CPU.

Some workloads are sensitive to network latency. 
In these cases, the overhead introduced by the router can limit the achievable throughput. 
This is when CPU amounts higher than two cores per router may be required.
On the other hand, some workloads are tolerant of network latency. 
In these cases, one core or less may be sufficient.

To get a better idea of performance in your environment, you can run benchmarks using Benchdog. Benchdog is a suite of containerized client-server benchmark tools. 
See the GitHub project for source code and instructions: https://github.com/skupperproject/benchdog

